In [90]:
#import libraries
import numpy as np
from scipy.linalg import lu
import matplotlib.pyplot as plt

# Problem 1

In [6]:
A_2x2 = np.array([[1.,  2.],
                  [3., -1.]])

B_2x2 = np.array([[3., -2.],
                  [2., 1.]])

C_3x1 = np.array([[1.],
                  [2.],
                  [3.]])

D_2x3 = np.array([[ 1., 3.,  1.],
                  [-2., 1., -1.]])

E_3x2 = np.array([[ 3., 1.],
                  [ 0., 3.],
                  [-2., 2.]])

F_2x3 = np.array([[ 2., 1.,  2.],
                  [-1., 3., -2.]])

In [7]:
AB = A_2x2 @ B_2x2
CD = C_3x1 @ D_2x3
EF = E_3x2 @ F_2x3

print(AB)
print(CD)
print(EF)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [ ]:
AT = np.linalg.matrix_transpose(A_2x2)
DT = np.linalg.matrix_transpose (D_2x3)
FT = np.linalg.matrix_transpose(F_2x3)

ATB = AT @ B_2x2
BDT = B_2x2 @ DT
DTFT = DT @ FT

print(ATB)
print(BDT)
print(DTFT)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

### The issues with the matrix multiplication are in the mismatch of indicies

# Problem 2

In [91]:
M_3x3 = np.array([[1, 0, 1],
                  [2, 2, 3],
                  [1, 2, 4]])

MInverse = np.linalg.inv(M_3x3)

print(MInverse)

M_3x3 @ MInverse


[[ 0.5   0.5  -0.5 ]
 [-1.25  0.75 -0.25]
 [ 0.5  -0.5   0.5 ]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Problem 3

In [92]:
P_3x3 = (1 / 7) * np.array([[ 3, -2, -6],
                            [-6, -3, -2],
                            [-2,  6, -3]])

PT = np.linalg.matrix_transpose(P_3x3)

print((P_3x3 @ PT).round(2))
print((PT @ P_3x3).round(2))

[[ 1. -0.  0.]
 [-0.  1. -0.]
 [ 0. -0.  1.]]
[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]


# Problem 4

In [93]:
X_4x4 = np.array([[-1, 3, 5,  2],
                  [ 1, 9, 8,  4],
                  [ 0, 1, 0,  1],
                  [ 2, 1, 1, -1]])

Y_4x1 = np.array([[10],
                  [15],
                  [ 2],
                  [-3]])

x = np.linalg.solve(X_4x4, Y_4x1).round(2)
print(x)

[[-1.]
 [ 0.]
 [ 1.]
 [ 2.]]


# Problem 5

In [94]:
ITERATION_LIMIT = 9

# initialize the matrix
A = np.array([[ 4., -1., -1.,  0.],
              [-1.,  4.,  0., -1.],
              [-1.,  0.,  4., -1.],
              [ 0., -1., -1.,  4.]])

# initialize the RHS vector
b = np.array([1., 2., 0., 1.])

print("System of equations:")
for i in range(A.shape[0]):
    row = [f"{A[i,j]:3g}*x{j+1}" for j in range(A.shape[1])]
    print("[{0}] = [{1:3g}]".format(" + ".join(row), b[i]))

x = np.zeros_like(b, np.float64)
for it_count in range(1, ITERATION_LIMIT):
    x_new = np.zeros_like(x, dtype=np.float64)
    print(f"Iteration {it_count}: {x}")
    for i in range(A.shape[0]):
        s1 = np.dot(A[i, :i], x_new[:i])
        s2 = np.dot(A[i, i + 1 :], x[i + 1 :])
        x_new[i] = (b[i] - s1 - s2) / A[i, i]
    if np.allclose(x, x_new, rtol=1e-8):
        break
    x = x_new

print(f"Solution: {x.round(2)}")
error = np.dot(A, x) - b
print(f"Error: {error}")

System of equations:
[  4*x1 +  -1*x2 +  -1*x3 +   0*x4] = [  1]
[ -1*x1 +   4*x2 +   0*x3 +  -1*x4] = [  2]
[ -1*x1 +   0*x2 +   4*x3 +  -1*x4] = [  0]
[  0*x1 +  -1*x2 +  -1*x3 +   4*x4] = [  1]
Iteration 1: [0. 0. 0. 0.]
Iteration 2: [0.25    0.5625  0.0625  0.40625]
Iteration 3: [0.40625   0.703125  0.203125  0.4765625]
Iteration 4: [0.4765625  0.73828125 0.23828125 0.49414062]
Iteration 5: [0.49414062 0.74707031 0.24707031 0.49853516]
Iteration 6: [0.49853516 0.74926758 0.24926758 0.49963379]
Iteration 7: [0.49963379 0.74981689 0.24981689 0.49990845]
Iteration 8: [0.49990845 0.74995422 0.24995422 0.49997711]
Solution: [0.5  0.75 0.25 0.5 ]
Error: [-6.86645508e-05 -1.71661377e-05 -1.71661377e-05  0.00000000e+00]


### It takes a minimum of 9 iterations for a error of 10^-5 or better

In [95]:
ITERATION_LIMIT = 9

# initialize the RHS vector
b = np.array([4., 2., 10., -2.])

print("System of equations:")
for i in range(A.shape[0]):
    row = [f"{A[i,j]:3g}*x{j+1}" for j in range(A.shape[1])]
    print("[{0}] = [{1:3g}]".format(" + ".join(row), b[i]))

x = np.zeros_like(b, np.float64)
for it_count in range(1, ITERATION_LIMIT):
    x_new = np.zeros_like(x, dtype=np.float64)
    print(f"Iteration {it_count}: {x}")
    for i in range(A.shape[0]):
        s1 = np.dot(A[i, :i], x_new[:i])
        s2 = np.dot(A[i, i + 1 :], x[i + 1 :])
        x_new[i] = (b[i] - s1 - s2) / A[i, i]
    if np.allclose(x, x_new, rtol=1e-8):
        break
    x = x_new

print(f"Solution: {x.round(2)}")
error = np.dot(A, x) - b
print(f"Error: {error}")

System of equations:
[  4*x1 +  -1*x2 +  -1*x3 +   0*x4] = [  4]
[ -1*x1 +   4*x2 +   0*x3 +  -1*x4] = [  2]
[ -1*x1 +   0*x2 +   4*x3 +  -1*x4] = [ 10]
[  0*x1 +  -1*x2 +  -1*x3 +   4*x4] = [ -2]
Iteration 1: [0. 0. 0. 0.]
Iteration 2: [1.    0.75  2.75  0.375]
Iteration 3: [1.875   1.0625  3.0625  0.53125]
Iteration 4: [2.03125   1.140625  3.140625  0.5703125]
Iteration 5: [2.0703125  1.16015625 3.16015625 0.58007812]
Iteration 6: [2.08007812 1.16503906 3.16503906 0.58251953]
Iteration 7: [2.08251953 1.16625977 3.16625977 0.58312988]
Iteration 8: [2.08312988 1.16656494 3.16656494 0.58328247]
Solution: [2.08 1.17 3.17 0.58]
Error: [-1.52587891e-04 -3.81469727e-05 -3.81469727e-05  0.00000000e+00]


# 6. (Problem 4.12)

In [111]:
def fwd_sub(L, b):
    n = len(b)
    x = np.zeros(n)

    for i in range(n):
        x[i] = (b[i] - np.dot(L[i, :i], x[:i])) / L[i, i]

    return x

def back_sub(U, b):
    n = len(b)
    x = np.zeros(n)

    for i in range (n -1, -1, -1):
        x[i] = (b[i] - np.dot(U[i, i+1:], x[i +1:])) / U[i, i]

    return x

def lu_inverse(A):
    A = A.astype(float)
    P, L, U = lu(A)
    n = A.shape[0]
    A_inv = np.zeros((n, n))

    for i in range(n):
        e_i = np.zeros(n)
        e_i[i] = 1

        y = fwd_sub(L, np.dot(P, e_i))
        x = back_sub(U, y)

        A_inv[:, i] = x

    return A_inv

In [112]:
print((lu_inverse(A) @ A).round(2))
print(A)


[[ 1.  0. -0. -0.]
 [-0.  1.  0. -0.]
 [ 0.  0.  1. -0.]
 [ 0.  0.  0.  1.]]
[[ 4. -1. -1.  0.]
 [-1.  4.  0. -1.]
 [-1.  0.  4. -1.]
 [ 0. -1. -1.  4.]]


In [113]:
def lu_det(A):
    P,L, U = lu(A)
    
    return np.prod(np.diag(U))

In [114]:
lu_det(A) == np.linalg.det(A)

np.True_

# 7. (NB)

In [115]:
A_2x2 = np.array([[0.780, 0.563],
                  [0.913, 0.659]])

b_2x1 = np.array([0.217, 0.254])

x_exact = np.array([1, -1])

x_alpha = np.array([0.999, -1.001])

x_beta = np.array([0.341, -0.087])

In [116]:
r_exact = b_2x1 - A_2x2 @ x_exact
r_alpha = b_2x1 - A_2x2 @ x_alpha
r_beta = b_2x1 - A_2x2 @ x_beta

print(f"x Exact residule:\n{r_exact}")
print(f"\nX Alpha residule:\n{r_alpha}")
print(f"\nX Beta residule:\n{r_beta}")

x Exact residule:
[-8.32667268e-17  0.00000000e+00]

X Alpha residule:
[0.001343 0.001572]

X Beta residule:
[1.e-06 0.e+00]


### X Beta has a smaller residule than X Alpha

In [117]:
A_det = np.linalg.det(A_2x2)
print(A_det)

1.000000000122681e-06


### The determinate shows that the Matrix is not well-posed

In [118]:
print(np.linalg.solve(A_2x2, b_2x1))

[ 1. -1.]


# 8. (Problem 4.26)

In [119]:
A = np.array([[ 4., -1., -1.,  0.],
              [-1.,  4.,  0., -1.],
              [-1.,  0.,  4., -1.],
              [ 0., -1., -1.,  4.]])

b = np.array([1., 2., 0., 1.])

In [120]:
def qrdec(A):
    n = A.shape[0]
    Ap = np.copy(A)
    Q = np.zeros((n, n))
    R = np.zeros((n, n))
    for j in range(n):
        for i in range(j):
            R[i, j] = Q[:, i] @ A[:, j]
            Ap[:, j] -= R[i, j] * Q[:, i]

        R[j, j] = np.linalg.norm(Ap[:, j])
        Q[:, j] = Ap[:, j] / R[j, j]
    return Q, R

In [121]:
Q, R = qrdec(A)
print((Q @ R).round(2))

[[ 4. -1. -1. -0.]
 [-1.  4.  0. -1.]
 [-1.  0.  4. -1.]
 [ 0. -1. -1.  4.]]


In [122]:
x = back_sub(R, Q.T @ b)
x

array([0.5 , 0.75, 0.25, 0.5 ])

# 9. (NB)

In [127]:
M_x = (1 / np.sqrt(2)) * np.array([[0, 1, 0],
                                   [1, 0, 1],
                                   [0, 1, 0]])


M_y = (1 / np.sqrt(2)) * np.array([[0, -1j, 0],
                                   [1j, 0, -1j],
                                   [0, 1j, 0]])

M_z = np.array([[1, 0, 0],
                [0, 0, 0],
                [0, 0, -1]])


In [129]:
def Commutator(A, B):
    commutation = (A @ B) - (B @ A)
    return commutation

In [134]:
print(Commutator(M_x, M_y))
print(1j * M_z)
Commutator(M_x, M_y).round(5) == (1j * M_z).round(5)

[[0.+1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.-1.j]]
[[ 0.+1.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -0.-1.j]]


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [137]:
print(Commutator(M_x, M_y).round(5) == (1j * M_z).round(5))
print(Commutator(M_z, M_x).round(5) == (1j * M_y).round(5))
print(Commutator(M_y, M_z).round(5) == (1j * M_x).round(5))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [149]:
((M_x @ M_x) + (M_y @ M_y) + (M_z @ M_z)).round(5) == 2 * np.identity(3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
L_plus = M_x + (1.j * M_y)
L_minus = M_x - (1.j * M_y)

In [144]:
Commutator(L_plus, L_minus).round(5) == (2 * M_z).round(5)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# 10. (NB)

In [156]:
L_plus = np.array([[0, 1, 0],
                   [0, 0, 1],
                   [0, 0, 0]])

L_minus = np.array([[0, 0, 0],
                    [1, 0, 0],
                    [0, 1, 0]])

ket_minus1 = np.array([0, 0, 1])

ket_zero = np.array([0, 1, 0])

ket_plus1 = np.array([1, 0, 0])

null = np. array ([0, 0, 0])

In [162]:
print(L_plus @ ket_minus1 == ket_zero)
print(L_minus @ ket_minus1 == null)
print(L_plus @ ket_zero == ket_plus1)
print(L_minus @ ket_zero == ket_minus1)
print(L_plus @ ket_plus1 == null)
print(L_minus @ ket_plus1 == ket_zero)

[ True  True  True]
[ True  True  True]
[ True  True  True]
[ True  True  True]
[ True  True  True]
[ True  True  True]
